# Generated by Django 5.2.17 on 2026-10-05 10:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowcellType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "output_m_read_pairs",
                    models.FloatField(
                        help_text="usable output in million read pairs (clusters)"
                    ),
                ),
                ("price_eur", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["output_m_read_pairs"],
            },
        ),
        migrations.CreateModel(
            name="IndexPrimer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("i7", "i7 (Index 1)"), ("i5", "i5 (Index 2)")],
                        max_length=2,
                    ),
                ),
                ("primer_id", models.CharField(max_length=40)),
                (
                    "sequence",
                    models.CharField(
                        help_text="i5: enter in the orientation stored in your primer sheet; the sample sheet export can reverse-complement it.",
                        max_length=40,
                    ),
                ),
                ("well", models.CharField(blank=True, max_length=4)),
            ],
            options={
                "ordering": ["index_set", "kind", "primer_id"],
            },
        ),
        migrations.CreateModel(
            name="IndexSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="WellBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode_id",
                    models.CharField(
                        help_text="e.g. BC01 — must match the barcode stock plate",
                        max_length=40,
                    ),
                ),
                (
                    "well",
                    models.CharField(
                        help_text="position in the 96-well barcode stock plate, e.g. A1",
                        max_length=4,
                    ),
                ),
                ("sequence", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ["barcode_set", "barcode_id"],
            },
        ),
        migrations.CreateModel(
            name="WellBarcodeSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="short ID used in pool and sample-sheet names, e.g. TP26-014",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "sharepoint_item_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "library_type",
                    models.CharField(
                        choices=[
                            ("tag_and_pool", "Tag&Pool (well barcodes)"),
                            ("bulk_rnaseq", "Bulk RNA-seq"),
                            ("sn_rnaseq", "Single-nucleus RNA-seq"),
                            (
                                "crispr_screen",
                                "Pooled CRISPR screen (sgRNA/barcode library)",
                            ),
                            ("other", "Other"),
                        ],
                        default="tag_and_pool",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("eln_assay_url", models.URLField(blank=True)),
                ("eln_libprep_url", models.URLField(blank=True)),
                ("lysis_date", models.DateField(blank=True, null=True)),
                ("delivery_deadline", models.DateField(blank=True, null=True)),
                ("r1_length", models.PositiveIntegerField(blank=True, null=True)),
                ("r2_length", models.PositiveIntegerField(blank=True, null=True)),
                ("i7_length", models.PositiveIntegerField(blank=True, null=True)),
                ("i5_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "requested_m_read_pairs",
                    models.FloatField(
                        blank=True,
                        help_text="total for the experiment, million read pairs",
                        null=True,
                    ),
                ),
                (
                    "library_complexity",
                    models.CharField(
                        choices=[
                            ("normal", "Normal / high"),
                            ("low", "Low (amplicon, sgRNA, barcode)"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "avg_product_length",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "avg_insert_length",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "planning_seed",
                    models.IntegerField(
                        blank=True,
                        help_text="random seed of the last automatic barcode layout",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("plan_in_review", "Barcode plan in review"),
                            ("plan_approved", "Barcode plan approved"),
                            ("libprep_done", "Library prep done"),
                            ("run_planned", "Run planned"),
                            ("submitted_to_provider", "Submitted to provider"),
                            ("data_delivered", "Data delivered"),
                            ("on_hold", "On hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("sharepoint_push_pending", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "responsible_assay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_libprep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_ngs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well_barcode_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planner.wellbarcodeset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFlowcellType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=80)),
                (
                    "output_m_read_pairs",
                    models.FloatField(
                        help_text="usable output in million read pairs (clusters)"
                    ),
                ),
                ("price_eur", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical flowcell type",
                "verbose_name_plural": "historical flowcell types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalIndexSet",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical index set",
                "verbose_name_plural": "historical index sets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSequencingRun",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "run_id",
                    models.SlugField(
                        help_text="e.g. NGS26-007 — written back to SharePoint",
                        max_length=40,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=100)),
                ("planned_submission_date", models.DateField(blank=True, null=True)),
                ("r1_length", models.PositiveIntegerField(blank=True, null=True)),
                ("r2_length", models.PositiveIntegerField(blank=True, null=True)),
                ("i7_length", models.PositiveIntegerField(blank=True, null=True)),
                ("i5_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "phix_percent",
                    models.FloatField(
                        blank=True,
                        help_text="empty = automatic (more PhiX if a low-complexity library is present)",
                        null=True,
                    ),
                ),
                (
                    "safety_margin_percent",
                    models.FloatField(
                        blank=True, help_text="empty = default from settings", null=True
                    ),
                ),
                (
                    "i5_reverse_complement",
                    models.BooleanField(
                        default=False,
                        help_text="Reverse-complement i5 in the sample sheet export. Ask your provider which orientation they expect.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_review", "Run plan in review"),
                            ("approved", "Run plan approved"),
                            ("submitted", "Submitted to provider"),
                            ("data_delivered", "Data delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "flowcell_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.flowcelltype",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sequencing run",
                "verbose_name_plural": "historical sequencing runs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWellBarcodeSet",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical well barcode set",
                "verbose_name_plural": "historical well barcode sets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPool",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "pool_id",
                    models.CharField(
                        help_text="unique within the experiment; used as Sample_ID in the sample sheet",
                        max_length=60,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.experiment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "i5",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"kind": "i5"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.indexprimer",
                    ),
                ),
                (
                    "i7",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"kind": "i7"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.indexprimer",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pool",
                "verbose_name_plural": "historical pools",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="indexprimer",
            name="index_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primers",
                to="planner.indexset",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalIndexPrimer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("i7", "i7 (Index 1)"), ("i5", "i5 (Index 2)")],
                        max_length=2,
                    ),
                ),
                ("primer_id", models.CharField(max_length=40)),
                (
                    "sequence",
                    models.CharField(
                        help_text="i5: enter in the orientation stored in your primer sheet; the sample sheet export can reverse-complement it.",
                        max_length=40,
                    ),
                ),
                ("well", models.CharField(blank=True, max_length=4)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "index_set",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.indexset",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical index primer",
                "verbose_name_plural": "historical index primers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pool_id",
                    models.CharField(
                        help_text="unique within the experiment; used as Sample_ID in the sample sheet",
                        max_length=60,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pools",
                        to="planner.experiment",
                    ),
                ),
                (
                    "i5",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "i5"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="planner.indexprimer",
                    ),
                ),
                (
                    "i7",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "i7"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="planner.indexprimer",
                    ),
                ),
            ],
            options={
                "ordering": ["experiment", "pool_id"],
            },
        ),
        migrations.CreateModel(
            name="SequencingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.SlugField(
                        help_text="e.g. NGS26-007 — written back to SharePoint",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=100)),
                ("planned_submission_date", models.DateField(blank=True, null=True)),
                ("r1_length", models.PositiveIntegerField(blank=True, null=True)),
                ("r2_length", models.PositiveIntegerField(blank=True, null=True)),
                ("i7_length", models.PositiveIntegerField(blank=True, null=True)),
                ("i5_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "phix_percent",
                    models.FloatField(
                        blank=True,
                        help_text="empty = automatic (more PhiX if a low-complexity library is present)",
                        null=True,
                    ),
                ),
                (
                    "safety_margin_percent",
                    models.FloatField(
                        blank=True, help_text="empty = default from settings", null=True
                    ),
                ),
                (
                    "i5_reverse_complement",
                    models.BooleanField(
                        default=False,
                        help_text="Reverse-complement i5 in the sample sheet export. Ask your provider which orientation they expect.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_review", "Run plan in review"),
                            ("approved", "Run plan approved"),
                            ("submitted", "Submitted to provider"),
                            ("data_delivered", "Data delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "flowcell_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planner.flowcelltype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="RunPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_m_read_pairs", models.FloatField(default=0)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_links",
                        to="planner.pool",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_pools",
                        to="planner.sequencingrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "pool__experiment", "pool__pool_id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalRunPool",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("target_m_read_pairs", models.FloatField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.pool",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.sequencingrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical run pool",
                "verbose_name_plural": "historical run pools",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Deviation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deviations",
                        to="planner.experiment",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deviations",
                        to="planner.sequencingrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("accept", "Experiment accepted"),
                            ("barcode_plan", "Barcode plan"),
                            ("libprep", "Library prep executed"),
                            ("run_plan", "Run plan"),
                            ("data_delivered", "Data delivered"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded (plan reopened)"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.JSONField(
                        default=dict, help_text="frozen copy of the plan at submission"
                    ),
                ),
                ("snapshot_hash", models.CharField(blank=True, max_length=64)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signoffs",
                        to="planner.experiment",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signoffs",
                        to="planner.sequencingrun",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_id", models.CharField(max_length=80)),
                (
                    "source_plate",
                    models.CharField(
                        blank=True,
                        help_text="culture plate ID, e.g. CULT01",
                        max_length=40,
                    ),
                ),
                (
                    "source_well",
                    models.CharField(
                        blank=True, help_text="A1..D6 for 24-well plates", max_length=4
                    ),
                ),
                ("condition", models.CharField(blank=True, max_length=200)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="row order of the uploaded sample list"
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="planner.experiment",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="samples",
                        to="planner.pool",
                    ),
                ),
                (
                    "well_barcode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planner.wellbarcode",
                    ),
                ),
            ],
            options={
                "ordering": ["experiment", "order", "sample_id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalSample",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("sample_id", models.CharField(max_length=80)),
                (
                    "source_plate",
                    models.CharField(
                        blank=True,
                        help_text="culture plate ID, e.g. CULT01",
                        max_length=40,
                    ),
                ),
                (
                    "source_well",
                    models.CharField(
                        blank=True, help_text="A1..D6 for 24-well plates", max_length=4
                    ),
                ),
                ("condition", models.CharField(blank=True, max_length=200)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="row order of the uploaded sample list"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.experiment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.pool",
                    ),
                ),
                (
                    "well_barcode",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.wellbarcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sample",
                "verbose_name_plural": "historical samples",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="wellbarcode",
            name="barcode_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="barcodes",
                to="planner.wellbarcodeset",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalWellBarcode",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "barcode_id",
                    models.CharField(
                        help_text="e.g. BC01 — must match the barcode stock plate",
                        max_length=40,
                    ),
                ),
                (
                    "well",
                    models.CharField(
                        help_text="position in the 96-well barcode stock plate, e.g. A1",
                        max_length=4,
                    ),
                ),
                ("sequence", models.CharField(max_length=40)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "barcode_set",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.wellbarcodeset",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical well barcode",
                "verbose_name_plural": "historical well barcodes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalExperiment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="short ID used in pool and sample-sheet names, e.g. TP26-014",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "sharepoint_item_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "library_type",
                    models.CharField(
                        choices=[
                            ("tag_and_pool", "Tag&Pool (well barcodes)"),
                            ("bulk_rnaseq", "Bulk RNA-seq"),
                            ("sn_rnaseq", "Single-nucleus RNA-seq"),
                            (
                                "crispr_screen",
                                "Pooled CRISPR screen (sgRNA/barcode library)",
                            ),
                            ("other", "Other"),
                        ],
                        default="tag_and_pool",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("eln_assay_url", models.URLField(blank=True)),
                ("eln_libprep_url", models.URLField(blank=True)),
                ("lysis_date", models.DateField(blank=True, null=True)),
                ("delivery_deadline", models.DateField(blank=True, null=True)),
                ("r1_length", models.PositiveIntegerField(blank=True, null=True)),
                ("r2_length", models.PositiveIntegerField(blank=True, null=True)),
                ("i7_length", models.PositiveIntegerField(blank=True, null=True)),
                ("i5_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "requested_m_read_pairs",
                    models.FloatField(
                        blank=True,
                        help_text="total for the experiment, million read pairs",
                        null=True,
                    ),
                ),
                (
                    "library_complexity",
                    models.CharField(
                        choices=[
                            ("normal", "Normal / high"),
                            ("low", "Low (amplicon, sgRNA, barcode)"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "avg_product_length",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "avg_insert_length",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "planning_seed",
                    models.IntegerField(
                        blank=True,
                        help_text="random seed of the last automatic barcode layout",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("plan_in_review", "Barcode plan in review"),
                            ("plan_approved", "Barcode plan approved"),
                            ("libprep_done", "Library prep done"),
                            ("run_planned", "Run planned"),
                            ("submitted_to_provider", "Submitted to provider"),
                            ("data_delivered", "Data delivered"),
                            ("on_hold", "On hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("sharepoint_push_pending", models.BooleanField(default=False)),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_assay",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_libprep",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_ngs",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well_barcode_set",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planner.wellbarcodeset",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical experiment",
                "verbose_name_plural": "historical experiments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="indexprimer",
            constraint=models.UniqueConstraint(
                fields=("index_set", "kind", "primer_id"), name="uniq_index_primer"
            ),
        ),
        migrations.AddConstraint(
            model_name="pool",
            constraint=models.UniqueConstraint(
                fields=("experiment", "pool_id"), name="uniq_pool"
            ),
        ),
        migrations.AddConstraint(
            model_name="runpool",
            constraint=models.UniqueConstraint(
                fields=("run", "pool"), name="uniq_run_pool"
            ),
        ),
        migrations.AddConstraint(
            model_name="sample",
            constraint=models.UniqueConstraint(
                fields=("experiment", "sample_id"), name="uniq_sample"
            ),
        ),
        migrations.AddConstraint(
            model_name="wellbarcode",
            constraint=models.UniqueConstraint(
                fields=("barcode_set", "barcode_id"), name="uniq_wbc_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="wellbarcode",
            constraint=models.UniqueConstraint(
                fields=("barcode_set", "well"), name="uniq_wbc_well"
            ),
        ),
    ]
