# Generated by Django 5.2.17 on 2026-10-06 13:28

from django.db import migrations, models


def convert_old_workflow(apps, schema_editor):
    """v0.1 approved the barcode plan per experiment BEFORE run planning; v0.2 approves barcodes +
    indexes together per run, before library prep. Map existing records onto the new statuses."""
    Experiment = apps.get_model("planner", "Experiment")
    RunPool = apps.get_model("planner", "RunPool")
    SignOff = apps.get_model("planner", "SignOff")
    SignOff.objects.filter(step="barcode_plan", state="pending").update(state="superseded")
    for e in Experiment.objects.all():
        link = RunPool.objects.filter(pool__experiment=e).select_related("run").order_by("-run__created").first()
        libprep = SignOff.objects.filter(experiment=e, step="libprep").exists()
        if link is None:
            new = "accepted" if e.status in ("plan_in_review", "plan_approved", "libprep_done", "run_planned") else e.status
        else:
            new = {"planning": "in_run", "in_review": "plan_in_review",
                   "approved": "libprep_done" if libprep else "plan_approved",
                   "submitted": "submitted_to_provider", "data_delivered": "data_delivered",
                   "cancelled": "accepted"}.get(link.run.status, e.status)
        if new != e.status:
            Experiment.objects.filter(pk=e.pk).update(status=new, sharepoint_push_pending=True)


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiment",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("accepted", "Accepted – in planning"),
                    ("in_run", "Assigned to NGS run"),
                    ("plan_in_review", "Final plan in review"),
                    ("plan_approved", "Plan approved – ready for library prep"),
                    ("libprep_done", "Library prep done"),
                    ("submitted_to_provider", "Submitted to provider"),
                    ("data_delivered", "Data delivered"),
                    ("on_hold", "On hold"),
                    ("cancelled", "Cancelled"),
                ],
                default="submitted",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="historicalexperiment",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("accepted", "Accepted – in planning"),
                    ("in_run", "Assigned to NGS run"),
                    ("plan_in_review", "Final plan in review"),
                    ("plan_approved", "Plan approved – ready for library prep"),
                    ("libprep_done", "Library prep done"),
                    ("submitted_to_provider", "Submitted to provider"),
                    ("data_delivered", "Data delivered"),
                    ("on_hold", "On hold"),
                    ("cancelled", "Cancelled"),
                ],
                default="submitted",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsequencingrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("in_review", "Final plan in review"),
                    ("approved", "Approved – library prep"),
                    ("submitted", "Submitted to provider"),
                    ("data_delivered", "Data delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="planning",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sequencingrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("in_review", "Final plan in review"),
                    ("approved", "Approved – library prep"),
                    ("submitted", "Submitted to provider"),
                    ("data_delivered", "Data delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="planning",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="signoff",
            name="step",
            field=models.CharField(
                choices=[
                    ("accept", "Experiment accepted"),
                    ("barcode_plan", "Barcode plan (old workflow, v0.1)"),
                    ("run_plan", "Final plan (well barcodes + sample indexes)"),
                    ("libprep", "Library prep executed"),
                    ("data_delivered", "Data delivered"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(convert_old_workflow, migrations.RunPython.noop),
    ]
