# Generated by Django 5.2.17 on 2026-10-06 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_workflow_plan_before_libprep"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiment",
            name="amendment_run",
            field=models.ForeignKey(
                blank=True,
                help_text="set while the plan of this experiment is reopened inside an approved run (amendment)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="amendments",
                to="planner.sequencingrun",
            ),
        ),
        migrations.AddField(
            model_name="historicalexperiment",
            name="amendment_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="set while the plan of this experiment is reopened inside an approved run (amendment)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="planner.sequencingrun",
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("accepted", "Accepted – in planning"),
                    ("in_run", "Assigned to NGS run"),
                    ("plan_in_review", "Final plan in review"),
                    ("plan_approved", "Plan approved – ready for library prep"),
                    ("amending", "Plan reopened – amendment"),
                    ("libprep_done", "Library prep done"),
                    ("submitted_to_provider", "Submitted to provider"),
                    ("data_delivered", "Data delivered"),
                    ("on_hold", "On hold"),
                    ("cancelled", "Cancelled"),
                ],
                default="submitted",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="historicalexperiment",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("accepted", "Accepted – in planning"),
                    ("in_run", "Assigned to NGS run"),
                    ("plan_in_review", "Final plan in review"),
                    ("plan_approved", "Plan approved – ready for library prep"),
                    ("amending", "Plan reopened – amendment"),
                    ("libprep_done", "Library prep done"),
                    ("submitted_to_provider", "Submitted to provider"),
                    ("data_delivered", "Data delivered"),
                    ("on_hold", "On hold"),
                    ("cancelled", "Cancelled"),
                ],
                default="submitted",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="signoff",
            name="step",
            field=models.CharField(
                choices=[
                    ("accept", "Experiment accepted"),
                    ("barcode_plan", "Barcode plan (old workflow, v0.1)"),
                    ("run_plan", "Final plan (well barcodes + sample indexes)"),
                    (
                        "amendment",
                        "Plan amendment (one experiment, re-checked across the run)",
                    ),
                    ("libprep", "Library prep executed"),
                    ("data_delivered", "Data delivered"),
                ],
                max_length=20,
            ),
        ),
    ]
