# Generated by Django 5.2.17 on 2026-10-10 06:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_plan_amendments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("library_type", models.CharField(max_length=20, unique=True)),
                ("layout", models.JSONField(default=list)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="experiment",
            name="library_layout",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="library structure P5 → P7: list of {type, label, length}",
            ),
        ),
        migrations.AddField(
            model_name="historicalexperiment",
            name="library_layout",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="library structure P5 → P7: list of {type, label, length}",
            ),
        ),
        migrations.AddField(
            model_name="historicalsample",
            name="plate_format",
            field=models.PositiveSmallIntegerField(
                default=24, help_text="culture plate format: 6, 12, 24, 48 or 96 wells"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="plate_format",
            field=models.PositiveSmallIntegerField(
                default=24, help_text="culture plate format: 6, 12, 24, 48 or 96 wells"
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="planning_seed",
            field=models.IntegerField(
                blank=True,
                help_text="random seed of the last automatic barcode layout (empty after manual drag & drop changes)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalexperiment",
            name="planning_seed",
            field=models.IntegerField(
                blank=True,
                help_text="random seed of the last automatic barcode layout (empty after manual drag & drop changes)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsample",
            name="source_well",
            field=models.CharField(
                blank=True, help_text="e.g. A1..D6 for 24-well plates", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="source_well",
            field=models.CharField(
                blank=True, help_text="e.g. A1..D6 for 24-well plates", max_length=4
            ),
        ),
        migrations.CreateModel(
            name="HistoricalLibraryTemplate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("library_type", models.CharField(db_index=True, max_length=20)),
                ("layout", models.JSONField(default=list)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical library template",
                "verbose_name_plural": "historical library templates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
