# Generated by Django 5.2.17 on 2026-10-10 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_plate_format_library_layout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="experiment",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="person responsible for the next step of this experiment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalexperiment",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="person responsible for the next step of this experiment",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsequencingrun",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="person responsible for the next step of this run",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sequencingrun",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="person responsible for the next step of this run",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
